export const SEED_FARMERS = [
  {
    id: "FMR-2024-0001",
    fullName: "Chikondi Banda",
    gender: "Female",
    dob: "1985-04-12",
    phone: "+265 991 234 567",
    altPhone: "",
    nationalId: "P12345678",
    district: "Lilongwe",
    ta: "T/A Kabudula",
    epa: "Chileka",
    section: "Mphande",
    village: "Mphande 1",
    gps: "-13.9626, 33.7741",
    association: "Lilongwe North Association",
    club: "Tiyanjane Club",
    group: "Tiyanjane Group A",
    memberNo: "LNA-001",
    farmSize: 2.5,
    unit: "Hectares",
    primaryCrops: ["Maize", "Groundnuts"],
    secondaryCrops: ["Soybeans"],
    productionSeason: "2023/2024",
    registrationDate: "2024-01-15",
    registrationOfficer: "John Phiri",
    status: "Active",
    photoUrl: null
  },
  {
    id: "FMR-2024-0002",
    fullName: "Moses Phiri",
    gender: "Male",
    dob: "1978-11-23",
    phone: "+265 882 345 678",
    altPhone: "+265 993 456 789",
    nationalId: "P87654321",
    district: "Mchinji",
    ta: "T/A Mkanda",
    epa: "Mkanda",
    section: "Chisenga",
    village: "Chisenga",
    gps: "-13.7928, 32.8802",
    association: "Mchinji Farmers Association",
    club: "Chikondano Club",
    group: "Chikondano Group B",
    memberNo: "MFA-082",
    farmSize: 4.0,
    unit: "Hectares",
    primaryCrops: ["Tobacco", "Maize"],
    secondaryCrops: [],
    productionSeason: "2023/2024",
    registrationDate: "2024-02-10",
    registrationOfficer: "Sarah Mwale",
    status: "Pending Verification",
    photoUrl: null
  },
  {
    id: "FMR-2024-0003",
    fullName: "Grace Mwale",
    gender: "Female",
    dob: "1990-02-05",
    phone: "+265 995 555 123",
    altPhone: "",
    nationalId: "P55512345",
    district: "Kasungu",
    ta: "T/A Mwase",
    epa: "Kasungu Boma",
    section: "Boma",
    village: "Kavala",
    gps: "-13.0333, 33.4833",
    association: "Kasungu Central Association",
    club: "Mtendere Club",
    group: "Mtendere Group C",
    memberNo: "KCA-104",
    farmSize: 1.5,
    unit: "Hectares",
    primaryCrops: ["Soybeans"],
    secondaryCrops: ["Beans"],
    productionSeason: "2023/2024",
    registrationDate: "2024-03-01",
    registrationOfficer: "Peter Zimba",
    status: "Active",
    photoUrl: null
  },
  {
    id: "FMR-2024-0004",
    fullName: "Elias Zimba",
    gender: "Male",
    dob: "1965-08-19",
    phone: "+265 888 111 222",
    altPhone: "",
    nationalId: "P88811122",
    district: "Mzimba",
    ta: "T/A M'mbelwa",
    epa: "Mzimba South",
    section: "Edingeni",
    village: "Edingeni",
    gps: "-11.9000, 33.6000",
    association: "Mzimba Farmers Trust",
    club: "Umodzi Club",
    group: "Umodzi Group D",
    memberNo: "MFT-211",
    farmSize: 5.0,
    unit: "Hectares",
    primaryCrops: ["Maize", "Beans"],
    secondaryCrops: ["Groundnuts"],
    productionSeason: "2023/2024",
    registrationDate: "2023-11-20",
    registrationOfficer: "John Phiri",
    status: "Inactive",
    photoUrl: null
  },
  {
    id: "FMR-2024-0005",
    fullName: "Luka Kamwendo",
    gender: "Male",
    dob: "1988-06-30",
    phone: "+265 999 888 777",
    altPhone: "",
    nationalId: "P99988877",
    district: "Lilongwe",
    ta: "T/A Kabudula",
    epa: "Chileka",
    section: "Mphande",
    village: "Mphande 2",
    gps: "-13.9630, 33.7750",
    association: "Lilongwe North Association",
    club: "Tiyanjane Club",
    group: "Tiyanjane Group A",
    memberNo: "LNA-002",
    farmSize: 1.2,
    unit: "Hectares",
    primaryCrops: ["Groundnuts"],
    secondaryCrops: [],
    productionSeason: "2023/2024",
    registrationDate: "2024-04-05",
    registrationOfficer: "Mary Zgambo",
    status: "Active",
    photoUrl: null
  }
];

export const SEED_GROUPS = [
  {
    id: "GRP-001",
    name: "Tiyanjane Group A",
    association: "Lilongwe North Association",
    club: "Tiyanjane Club",
    village: "Mphande 1",
    district: "Lilongwe",
    members: 24,
    chairperson: "Chikondi Banda",
    status: "Active",
    createdAt: "2023-10-15"
  },
  {
    id: "GRP-002",
    name: "Chikondano Group B",
    association: "Mchinji Farmers Association",
    club: "Chikondano Club",
    village: "Chisenga",
    district: "Mchinji",
    members: 15,
    chairperson: "Moses Phiri",
    status: "Active",
    createdAt: "2023-09-12"
  },
  {
    id: "GRP-003",
    name: "Mtendere Group C",
    association: "Kasungu Central Association",
    club: "Mtendere Club",
    village: "Kavala",
    district: "Kasungu",
    members: 30,
    chairperson: "Grace Mwale",
    status: "Active",
    createdAt: "2023-11-01"
  },
  {
    id: "GRP-004",
    name: "Umodzi Group D",
    association: "Mzimba Farmers Trust",
    club: "Umodzi Club",
    village: "Edingeni",
    district: "Mzimba",
    members: 18,
    chairperson: "Elias Zimba",
    status: "Inactive",
    createdAt: "2022-05-20"
  }
];

export const SEED_HISTORY = [
  {
    id: "HIST-001",
    farmerId: "FMR-2024-0001",
    farmerName: "Chikondi Banda",
    date: "2024-01-15T09:30:00Z",
    type: "Registration",
    description: "Farmer registered in the system",
    officer: "John Phiri",
    location: "Mphande 1"
  },
  {
    id: "HIST-002",
    farmerId: "FMR-2024-0001",
    farmerName: "Chikondi Banda",
    date: "2024-02-10T14:15:00Z",
    type: "Farm Visit",
    description: "Agronomic advisory provided for Maize crop",
    officer: "Mary Zgambo",
    location: "Mphande 1"
  },
  {
    id: "HIST-003",
    farmerId: "FMR-2024-0002",
    farmerName: "Moses Phiri",
    date: "2024-02-10T11:20:00Z",
    type: "Registration",
    description: "Farmer registered in the system",
    officer: "Sarah Mwale",
    location: "Chisenga"
  },
  {
    id: "HIST-004",
    farmerId: "FMR-2024-0003",
    farmerName: "Grace Mwale",
    date: "2024-03-01T08:45:00Z",
    type: "Registration",
    description: "Farmer registered in the system",
    officer: "Peter Zimba",
    location: "Kavala"
  },
  {
    id: "HIST-005",
    farmerId: "FMR-2024-0001",
    farmerName: "Chikondi Banda",
    date: "2024-04-12T10:00:00Z",
    type: "Seed Loan",
    description: "Received 10kg of Maize seed loan",
    officer: "John Phiri",
    location: "Lilongwe North EPA"
  },
  {
    id: "HIST-006",
    farmerId: "FMR-2024-0005",
    farmerName: "Luka Kamwendo",
    date: "2024-04-05T13:30:00Z",
    type: "Registration",
    description: "Farmer registered in the system",
    officer: "Mary Zgambo",
    location: "Mphande 2"
  }
];

export const SEED_TRACEABILITY = [
  {
    id: "TRC-001",
    farmerId: "FMR-2024-0001",
    batchNumber: "BCH-2024-1045",
    bagNumber: "BAG-8992",
    commodity: "Maize",
    quantity: 50,
    warehouse: "Lilongwe Main Silo",
    purchaseDate: "2024-05-12",
    purchaseValue: 15000,
    status: "Stored"
  },
  {
    id: "TRC-002",
    farmerId: "FMR-2024-0001",
    batchNumber: "BCH-2024-1045",
    bagNumber: "BAG-8993",
    commodity: "Maize",
    quantity: 50,
    warehouse: "Lilongwe Main Silo",
    purchaseDate: "2024-05-12",
    purchaseValue: 15000,
    status: "Stored"
  },
  {
    id: "TRC-003",
    farmerId: "FMR-2024-0001",
    batchNumber: "BCH-2024-1102",
    bagNumber: "BAG-9104",
    commodity: "Groundnuts",
    quantity: 40,
    warehouse: "Lilongwe Annex",
    purchaseDate: "2024-06-01",
    purchaseValue: 32000,
    status: "In Transit"
  }
];

export const SEED_DOCUMENTS = [
  {
    id: "DOC-001",
    farmerId: "FMR-2024-0001",
    name: "National ID Copy",
    type: "National ID",
    uploadDate: "2024-01-15",
    uploadedBy: "John Phiri",
    status: "Verified",
    url: "/mock-docs/id.pdf"
  },
  {
    id: "DOC-002",
    farmerId: "FMR-2024-0001",
    name: "Land Registration Form",
    type: "Land Certificate",
    uploadDate: "2024-01-15",
    uploadedBy: "John Phiri",
    status: "Verified",
    url: "/mock-docs/land.pdf"
  },
  {
    id: "DOC-003",
    farmerId: "FMR-2024-0001",
    name: "Association Membership",
    type: "Membership Certificate",
    uploadDate: "2024-02-10",
    uploadedBy: "Mary Zgambo",
    status: "Pending",
    url: "/mock-docs/membership.jpg"
  }
];