export const mockNotifications = [
  {
    id: 1,
    title: "New user created",
    message: "System Administrator created a new Warehouse Officer account",
    type: "System",
    read: false,
    createdAt: "5 minutes ago",
    date: "Today",
  },
  {
    id: 2,
    title: "Warehouse updated",
    message: "Warehouse WH001 capacity information was changed",
    type: "System",
    read: false,
    createdAt: "20 minutes ago",
    date: "Today",
  },
  {
    id: 3,
    title: "Purchase transaction completed",
    message: "Purchase order PO-2026-0042 approved and completed",
    type: "Purchasing",
    read: false,
    createdAt: "1 hour ago",
    date: "Today",
  },
  {
    id: 4,
    title: "Stock level alert",
    message: "Inventory at WH003 Mzimba Depot is below minimum threshold",
    type: "Inventory",
    read: false,
    createdAt: "2 hours ago",
    date: "Today",
  },
  {
    id: 5,
    title: "Permission role updated",
    message: "IPC Manager role permissions updated by System Administrator",
    type: "System",
    read: false,
    createdAt: "3 hours ago",
    date: "Today",
  },
  {
    id: 6,
    title: "Batch traceability record created",
    message: "Batch BT-2026-0019 traceability chain of custody registered",
    type: "Traceability",
    read: true,
    createdAt: "Yesterday, 4:15 PM",
    date: "Yesterday",
  },
  {
    id: 7,
    title: "Audit log export completed",
    message: "Quarterly audit log export has been generated and is ready for download",
    type: "System",
    read: true,
    createdAt: "Yesterday, 2:00 PM",
    date: "Yesterday",
  },
  {
    id: 8,
    title: "New farmer registered",
    message: "25 new farmer profiles registered under Farmer Group FG-Mchinji-08",
    type: "Farmers",
    read: true,
    createdAt: "Yesterday, 10:30 AM",
    date: "Yesterday",
  },
];
