// ─────────────────────────────────────────────────────────────
// NASFAM GTMS — Mock IPC Data
// Interprofessional Committee (IPC) operations data
// ─────────────────────────────────────────────────────────────

export const mockIPCs = [
  {
    id: "ipc-001",
    name: "Lilongwe IPC",
    district: "Lilongwe",
    region: "Central",
    registrationNumber: "IPC/LLW/001",
    establishmentDate: "2020-03-15",
    status: "Active",
    chairperson: "Alex Banda",
    chairpersonPhone: "+265 999 111 001",
    secretaryName: "Elizabeth Mwale",
    secretaryPhone: "+265 999 111 002",
    address: "Plot 234, Lilongwe City Center",
    totalFarmers: 450,
    totalWarehouses: 2,
    warehouseCapacity: "5000 MT",
    lastActivityDate: "2024-07-13",
    contactEmail: "lilongwe@nasfam.org",
  },
  {
    id: "ipc-002",
    name: "Mchinji IPC",
    district: "Mchinji",
    region: "Central",
    registrationNumber: "IPC/MCH/002",
    establishmentDate: "2019-06-20",
    status: "Active",
    chairperson: "Peter Zulu",
    chairpersonPhone: "+265 999 111 003",
    secretaryName: "Grace Nkomo",
    secretaryPhone: "+265 999 111 004",
    address: "Plot 567, Mchinji Market",
    totalFarmers: 320,
    totalWarehouses: 1,
    warehouseCapacity: "3000 MT",
    lastActivityDate: "2024-07-12",
    contactEmail: "mchinji@nasfam.org",
  },
  {
    id: "ipc-003",
    name: "Kasungu IPC",
    district: "Kasungu",
    region: "Central",
    registrationNumber: "IPC/KAS/003",
    establishmentDate: "2021-01-10",
    status: "Active",
    chairperson: "James Nkhata",
    chairpersonPhone: "+265 999 111 005",
    secretaryName: "Rebecca Lungu",
    secretaryPhone: "+265 999 111 006",
    address: "Plot 890, Kasungu Town",
    totalFarmers: 280,
    totalWarehouses: 1,
    warehouseCapacity: "2500 MT",
    lastActivityDate: "2024-07-13",
    contactEmail: "kasungu@nasfam.org",
  },
  {
    id: "ipc-004",
    name: "Mzimba IPC",
    district: "Mzimba",
    region: "Northern",
    registrationNumber: "IPC/MZB/004",
    establishmentDate: "2020-09-05",
    status: "Active",
    chairperson: "Thomas Kumwenda",
    chairpersonPhone: "+265 999 111 007",
    secretaryName: "Catherine Njolwa",
    secretaryPhone: "+265 999 111 008",
    address: "Plot 123, Mzimba Trading Centre",
    totalFarmers: 390,
    totalWarehouses: 2,
    warehouseCapacity: "4500 MT",
    lastActivityDate: "2024-07-11",
    contactEmail: "mzimba@nasfam.org",
  },
];

// IPC warehouse data
export const mockIPCWarehouses = [
  {
    id: "wh-001",
    ipcId: "ipc-001",
    ipcName: "Lilongwe IPC",
    name: "Lilongwe Main Warehouse",
    location: "Lilongwe City",
    capacity: "3000 MT",
    currentStock: "2145 MT",
    capacity_utilization: 71.5,
    lastUpdated: "2024-07-13T10:00:00Z",
    status: "Operational",
    commodities: ["Maize", "Soybean", "Groundnuts"],
  },
  {
    id: "wh-002",
    ipcId: "ipc-001",
    ipcName: "Lilongwe IPC",
    name: "Lilongwe Secondary Warehouse",
    location: "Lilongwe Suburbs",
    capacity: "2000 MT",
    currentStock: "890 MT",
    capacity_utilization: 44.5,
    lastUpdated: "2024-07-13T09:30:00Z",
    status: "Operational",
    commodities: ["Maize", "Sunflower"],
  },
  {
    id: "wh-003",
    ipcId: "ipc-002",
    ipcName: "Mchinji IPC",
    name: "Mchinji Market Warehouse",
    location: "Mchinji Market",
    capacity: "3000 MT",
    currentStock: "1567 MT",
    capacity_utilization: 52.2,
    lastUpdated: "2024-07-13T11:15:00Z",
    status: "Operational",
    commodities: ["Maize", "Groundnuts"],
  },
  {
    id: "wh-004",
    ipcId: "ipc-003",
    ipcName: "Kasungu IPC",
    name: "Kasungu Central Warehouse",
    location: "Kasungu Town",
    capacity: "2500 MT",
    currentStock: "1234 MT",
    capacity_utilization: 49.4,
    lastUpdated: "2024-07-13T12:45:00Z",
    status: "Operational",
    commodities: ["Maize", "Soybean"],
  },
];

// IPC performance metrics
export const mockIPCMetrics = {
  "ipc-001": {
    totalFarmers: 450,
    activeFarmers: 425,
    totalPurchases: 2345,
    totalWeight: "58,250 kg",
    averagePricePerKg: "MWK 3,450",
    monthlyGrowth: 8.5,
    warehouseUtilization: 58.0,
    syncStatus: "Synced",
  },
  "ipc-002": {
    totalFarmers: 320,
    activeFarmers: 298,
    totalPurchases: 1678,
    totalWeight: "42,100 kg",
    averagePricePerKg: "MWK 3,250",
    monthlyGrowth: 5.2,
    warehouseUtilization: 52.2,
    syncStatus: "Synced",
  },
  "ipc-003": {
    totalFarmers: 280,
    activeFarmers: 267,
    totalPurchases: 1234,
    totalWeight: "31,200 kg",
    averagePricePerKg: "MWK 3,100",
    monthlyGrowth: 3.8,
    warehouseUtilization: 49.4,
    syncStatus: "Synced",
  },
  "ipc-004": {
    totalFarmers: 390,
    activeFarmers: 378,
    totalPurchases: 2012,
    totalWeight: "50,450 kg",
    averagePricePerKg: "MWK 3,400",
    monthlyGrowth: 6.1,
    warehouseUtilization: 51.0,
    syncStatus: "Synced",
  },
};
